
"""Alterar data_inicio e data_final para DateTime em eventos

Revision ID: 369018d8a13d
Revises: 3cbbf54841d0
Create Date: 2025-09-11 12:32:07.649347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '369018d8a13d'
down_revision = '3cbbf54841d0'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('eventos', 'data_inicio',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('eventos', 'data_final',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('eventos', 'data_final',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('eventos', 'data_inicio',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    # ### end Alembic commands ###