
"""add tipo to membros

Revision ID: 39ed2f910ac0
Revises: fb4474f3dbd9
Create Date: 2025-09-10 13:43:06.172513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39ed2f910ac0'
down_revision = 'fb4474f3dbd9'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('membros', sa.Column('tipo', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('membros', 'tipo')
    # ### end Alembic commands ###