
"""add caixas projetos e missionaria

Revision ID: a182818da41c
Revises: 20230903_ices_initial
Create Date: 2025-09-04 13:32:40.151801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a182818da41c'
down_revision = '20230903_ices_initial'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('membros', 'foto',
               existing_type=sa.BLOB(),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('membros', 'foto',
               existing_type=sa.String(length=255),
               type_=sa.BLOB(),
               existing_nullable=True)
    # ### end Alembic commands ###