
"""add caixas projetos e missionaria

Revision ID: fb4474f3dbd9
Revises: a182818da41c
Create Date: 2025-09-04 13:39:25.494315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb4474f3dbd9'
down_revision = 'a182818da41c'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saidas_missionarias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=255), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saidas_missionarias_id'), 'saidas_missionarias', ['id'], unique=False)
    op.create_table('saidas_projetos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=255), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saidas_projetos_id'), 'saidas_projetos', ['id'], unique=False)
    op.create_table('entradas_missionarias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=255), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('membro_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['membro_id'], ['membros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entradas_missionarias_id'), 'entradas_missionarias', ['id'], unique=False)
    op.create_table('entradas_projetos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=255), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('membro_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['membro_id'], ['membros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entradas_projetos_id'), 'entradas_projetos', ['id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entradas_projetos_id'), table_name='entradas_projetos')
    op.drop_table('entradas_projetos')
    op.drop_index(op.f('ix_entradas_missionarias_id'), table_name='entradas_missionarias')
    op.drop_table('entradas_missionarias')
    op.drop_index(op.f('ix_saidas_projetos_id'), table_name='saidas_projetos')
    op.drop_table('saidas_projetos')
    op.drop_index(op.f('ix_saidas_missionarias_id'), table_name='saidas_missionarias')
    op.drop_table('saidas_missionarias')
    # ### end Alembic commands ###